## Try 5.1.1: Data wrangling with Python.

The Python code below constructs the dataframe example. The code then displays the contents of example, displays dataframe information, selects a slice, and sorts example on the Continent column.

Modify the code as follows:

   * **Click the double-right arrow to restart the kernel and run all cells.**

   * **In the statement example = pd.DataFrame(), add a fourth column 'OfficialLanguage' with the values in the iamge above.**

   * **Run the code again and verify your changes are correct.**

**Now, modify the code to create a new dataframe country:**


* **Import the file country.csv with the statement country = pd.read_csv("country.csv").**

* **Display country and verify the data is identical to the image above.**

* **Display dataframe information and review the data types of each column.**

* **Display the population of Norway using country.at[].**

**Sort country on the Continent column, ascending, and display the result.**

In [1]:
# Import Pandas package
import pandas as pd

In [2]:
# Construct dataframe example
example = pd.DataFrame(
    data=[
        ['China', 'Asia', 9572900],
        ['Bangladesh', 'Asia', 143998],
        ['Brazil', 'South America', 8547403],
        ['Norway', 'Europe', 358207],
    ],
    columns=['Country', 'Continent', 'Population'],
)

# Display example
example

      Country      Continent  Population
0       China           Asia     9572900
1  Bangladesh           Asia      143998
2      Brazil  South America     8547403
3      Norway         Europe      358207

In [3]:
# Show information about example
example.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Columns: 3 entries, Country to Population
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [8]:
# Display rows 1 through 3 and columns Country through Continent
example.loc[1:3, 'Country':'Continent']

      Country      Continent
1  Bangladesh           Asia
2      Brazil  South America
3      Norway         Europe

In [4]:
# Sort example on Continent
example.sort_values('Continent', ascending=False, inplace=True)

# Display sorted data
example

      Country      Continent  Population
2      Brazil  South America     8547403
3      Norway         Europe      358207
0       China           Asia     9572900
1  Bangladesh           Asia      143998