## Cleaning data with Python.

In [1]:
# Import packages
import pandas as pd

# Import dataset
auto = pd.read_csv("autodata.csv")

# Display auto
auto

  Manufacturer        Model  Drive EngineType  Cylinders  Liters    MPG
0         Audi           A4    All        Gas        4.0     2.0   24.0
1          BMW       328 Ci   Rear        Gas        6.0     3.6   20.0
2      Bentley  Continental   Rear        Gas        NaN     NaN  210.0
3    Chevrolet       Malibu  Front        Gas        6.0     3.6   18.0
4         Ford      Mustang   Rear        Gas        6.0     3.7    NaN
5  Rolls-Royce        Ghost   Rear        Gas       12.0     6.6   12.0
6    Chevrolet       Malibu  Front        Gas        6.0     3.6   18.0

In [3]:
# Which rows have missing values?
auto.isnull()

   Manufacturer  Model  Drive  EngineType  Cylinders  Liters    MPG
0         False  False  False       False      False   False  False
1         False  False  False       False      False   False  False
2         False  False  False       False       True    True  False
3         False  False  False       False      False   False  False
4         False  False  False       False      False   False   True
5         False  False  False       False      False   False  False
6         False  False  False       False      False   False  False

In [7]:
# Count the colm with missing values for each feature
auto.isnull().sum()

Manufacturer    0
Model           0
Drive           0
EngineType      0
Cylinders       1
Liters          1
MPG             1
dtype: int64

In [9]:
# Remove duplicates from dataset
auto.drop_duplicates(inplace=True)
auto

  Manufacturer        Model  Drive EngineType  Cylinders  Liters    MPG
0         Audi           A4    All        Gas        4.0     2.0   24.0
1          BMW       328 Ci   Rear        Gas        6.0     3.6   20.0
2      Bentley  Continental   Rear        Gas        NaN     NaN  210.0
3    Chevrolet       Malibu  Front        Gas        6.0     3.6   18.0
4         Ford      Mustang   Rear        Gas        6.0     3.7    NaN
5  Rolls-Royce        Ghost   Rear        Gas       12.0     6.6   12.0

In [11]:
# Remove rows with missing values for both Cylinders and Liters
auto.dropna(subset=['Cylinders', 'Liters'], how='all', inplace=True)
auto

  Manufacturer    Model  Drive EngineType  Cylinders  Liters   MPG
0         Audi       A4    All        Gas        4.0     2.0  24.0
1          BMW   328 Ci   Rear        Gas        6.0     3.6  20.0
3    Chevrolet   Malibu  Front        Gas        6.0     3.6  18.0
4         Ford  Mustang   Rear        Gas        6.0     3.7   NaN
5  Rolls-Royce    Ghost   Rear        Gas       12.0     6.6  12.0

In [13]:
# Remove features with missing values in a given row
auto.dropna(axis=1, subset=[3])
auto

  Manufacturer    Model  Drive EngineType  Cylinders  Liters   MPG
0         Audi       A4    All        Gas        4.0     2.0  24.0
1          BMW   328 Ci   Rear        Gas        6.0     3.6  20.0
3    Chevrolet   Malibu  Front        Gas        6.0     3.6  18.0
4         Ford  Mustang   Rear        Gas        6.0     3.7   NaN
5  Rolls-Royce    Ghost   Rear        Gas       12.0     6.6  12.0

In [15]:
# Compute mean values of numeric features
mean = auto.mean(numeric_only=True)
auto.fillna(value=mean, inplace=True)
auto

  Manufacturer    Model  Drive EngineType  Cylinders  Liters   MPG
0         Audi       A4    All        Gas        4.0     2.0  24.0
1          BMW   328 Ci   Rear        Gas        6.0     3.6  20.0
3    Chevrolet   Malibu  Front        Gas        6.0     3.6  18.0
4         Ford  Mustang   Rear        Gas        6.0     3.7  18.5
5  Rolls-Royce    Ghost   Rear        Gas       12.0     6.6  12.0

## challenge activity 5.4.2: Cleaning data using pandas.

## This dataset contains information on lifestyle measures such as the amount of sunshine, pollution, and happiness levels for 44 major cities around the world.

* **Drop instances with duplicate values of sunshine_hours from the dataset.**
* 
**The code contains all imports, loads the dataset, and displays healthyClean.info().**

In [1]:
# Import packages and functions
import pandas as pd

# Load the dataset
healthy = pd.read_csv('healthy_example.csv')

# Remove instances with duplicate values of sunshine_hours 
healthyClean = healthy.drop_duplicates(subset=['sunshine_hours'])

healthyClean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 0 to 43
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   cost_bottled_water     39 non-null     object
 1   annual_hours_worked    29 non-null     float64
 2   sunshine_hours         39 non-null     float64
 3   number_takeout_places  39 non-null     float64
dtypes: float64(3), object(1)
memory usage: 1.6+ KB

# 2

**This dataset contains information on lifestyle measures such as the amount of sunshine, pollution, and happiness levels for 44 major cities around the world.**

* **Drop features with missing values of instance 11 from the dataset.**

**The code contains all imports, loads the dataset, and displays lifestyleClean.info().**

In [4]:
# Import packages and functions
import pandas as pd

# Load the dataset
lifestyle = pd.read_csv('healthy_example.csv')

# Remove features with missing values of 11
lifestyleClean = lifestyle.dropna(thresh=11)

lifestyleClean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   cost_bottled_water     0 non-null      object
 1   annual_hours_worked    0 non-null      float64
 2   sunshine_hours         0 non-null      float64
 3   number_takeout_places  0 non-null      float64
dtypes: float64(3), object(1)
memory usage: 0.0+ bytes

# 3) **This dataset contains information on lifestyle measures such as the amount of sunshine, pollution, and happiness levels for 44 major cities around the world.**

* **Calculate and print the mean value of sunshine_hours.**

* **Replace the missing values of sunshine_hours in place with the mean of sunshine_hours.**

**The code contains all imports, loads the dataset, and displays healthy['sunshine_hours'].**

In [5]:
# Import packages and functions
import pandas as pd

# Load the dataset
healthy = pd.read_csv('healthy_example.csv')

# Calculate the mean values of the features
healthyMean = healthy.mean(numeric_only=True)
print('Mean:', healthyMean['sunshine_hours'], '\n')

# Replace missing values of sunshine_hours in place with the mean of sunshine_hours
healthy['sunshine_hours'].fillna(healthyMean['sunshine_hours'], inplace=True)

print(healthy['sunshine_hours'])

Mean: 2245.860465116279

0     1858.000000
1     2636.000000
2     1884.000000
3     1821.000000
4     1630.000000
5     1662.000000
6     2769.000000
7     1626.000000
8     2591.000000
9     1938.000000
10    2363.000000
11    2671.000000
12    2624.000000
13    2525.000000
14    2066.000000
15    2769.000000
16    2983.000000
17    2066.000000
18    1662.000000
19    2245.860465
20    3311.000000
21    2218.000000
22    3542.000000
23    1405.000000
24    3254.000000
25    2584.000000
26    2634.000000
27    1453.000000
28    1877.000000
29    2508.000000
30    1836.000000
31    1776.000000
32    1546.000000
33    3062.000000
34    1662.000000
35    2003.000000
36    1566.000000
37    1633.000000
38    3124.000000
39    1915.000000
40    2528.000000
41    2535.000000
42    1901.000000
43    2555.000000
Name: sunshine_hours, dtype: float64

/tmp/ipykernel_31464/4019939036.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  healthy['sunshine_hours'].fillna(healthyMean['sunshine_hours'], inplace=True)